# Generated by Django 3.1.7 on 2021-04-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210321_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_quiz',
            name='level',
            field=models.IntegerField(),
        ),
    ]
