# Generated by Django 3.1.7 on 2021-04-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210403_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked',
            field=models.BooleanField(default=False),
        ),
    ]
