# Generated by Django 3.1.7 on 2021-04-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Win_Payment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
