# Generated by Django 3.1.7 on 2021-04-06 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210406_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 0, 18, 19, 537149)),
        ),
    ]
