# Generated by Django 3.2.5 on 2021-07-01 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210406_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 14, 38, 56, 251072)),
        ),
    ]
