# Generated by Django 3.2.5 on 2021-07-04 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 4, 6, 57, 8, 816389)),
        ),
    ]
